export const markers = [
  {
    id: 1,
    city: "Goes",
    country: "NETHERLANDS",
    address: "",
    olgcs: "-",
    vault: "",
    valueOlgcs: "",
    color: "red",
    coordinates: [51.504646, 3.891130],
    value: 80,
  },
  {
    id: 2,
    city: "Antwerp",
    country: "Belgium",
    vault: "-",
    address: "-",
    olgcs: "-",
    valueOlgcs: "-",
    color: "blue",
    coordinates: [51.260197, 4.402771],
    value: 80,
  },
  {
    id: 3,
    city: "Berlin",
    country: "Germany",
    address: "-",
    olgcs: "-",
    vault: "-",
    valueOlgcs: "-",
    color: "orange",
    coordinates: [52.520008, 13.404954],
    value: 75,
  },
  {
    id: 4,
    city: "Vienna",
    country: "Austria",
    address: "-",
    olgcs: "-",
    vault: "-",
    valueOlgcs: "-",
    color: "gold",
    coordinates: [48.210033, 16.363449],
    value: 135,
  },
  {
    id: 5,
    city: "Hässleholm",
    country: "Sweden",
    address: "-",
    olgcs: "-",
    vault: "-",
    valueOlgcs: "-",
    color: "green",
    coordinates: [56.158913, 13.766765 ],
    value: 80,
  },
  {
    id: 6,
    city: "Rovaniemi",
    country: "Finland",
    address: "",
    olgcs: "-",
    vault: "",
    valueOlgcs: "",
    color: "red",
    coordinates: [66.503059, 25.726967],
    value: 80,
  },
];
